export const base = {
  colors: {
    primary: '#5051F9',
    background: '#141516',
    disabledSideBarButton: '#5F6388',
    secondaryBackground: '#1E1F25',
    disabledPrimary: '#83BDD5',
    black: '#001117',
    red: '#CD4F4F',
    skyBlue: '#0094CF',
    lightSkyBlue: '#F0F6FA',
    btnPrimaryDisabled: '#82BDD5',
    btnPrimaryDisabledGray: '#B8D3DD',
    microsoftBtn: '#2F2F2F',
    gray1: '#66737C',
    gray2: '#9A9A9A',
    grey: '#F8F8F8',
    darkGray: '#3C3C3B',
    lightGray: '#D9D9D9',
    secondaries: {
      purple: '#6E1242',
      green: '#1D7D54',
    },
  },
  fonts: {
    primary: 'Figtree, Segoe UI, Roboto, system-ui, sans-serif',
    bold: 'Figtree-Bold, Segoe UI, Roboto, system-ui, sans-serif',
    semiBold: 'Figtree-SemiBold, Segoe UI, Roboto, system-ui, sans-serif',
    medium: 'Figtree-Medium, Segoe UI, Roboto, system-ui, sans-serif',
    regular: 'Figtree-Regular, system-ui, sans-serif',
    light: 'Figtree-Regular, system-ui, sans-serif',
    saeLogo: 'Georgia, Times New Roman, Times, serif',
    microsoftBtn: 'Segoe-UI, Tahoma, Geneva, Verdana, sans-serif',
  },
};
